services:

##########################################
##
## network infrastructure
##
##########################################

    shinobi-proxy:

        container_name: shinobi-proxy

        image: nginxproxy/nginx-proxy

        restart: unless-stopped

        ports:

            - "80:80"

            - "443:443"

        volumes:

            - /var/run/docker.sock:/tmp/docker.sock:ro

            - /var/docker/nginx/html:/usr/share/nginx/html

            - /var/docker/nginx/certs:/etc/nginx/certs

            - /var/docker/nginx/vhost:/etc/nginx/vhost.d

        logging:

            options:

                max-size: "10m"

                max-file: "3"

    shinobi-letsencrypt:

        container_name: shinobi-letsencrypt

        image: jrcs/letsencrypt-nginx-proxy-companion

        restart: unless-stopped

        volumes_from:

            - shinobi-proxy

        volumes:

            - /var/run/docker.sock:/var/run/docker.sock

            - /var/docker/nginx/acme:/etc/acme.sh

        environment:

            DEFAULT_EMAIL: workspace@valorantsoftware.digital

##########################################
##
## storage infrastructure
##
##########################################

    shinobi-database:

        container_name: shinobi-database

        image: mariadb

        volumes:

            - .volumes/mariadb:/var/lib/mysql

        ports:
    
            - "3306:3306"

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: shinobipublicapis

            MYSQL_USER: shinobipublicapis

            MYSQL_PASSWORD: shinobipublicapis

    shinobi-phpmyadmin:

        container_name: shinobi-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - shinobi-database

        links:

           - shinobi-database

        ports:

            - "3380:80"

        environment:

            PMA_HOST: shinobi-database

            VIRTUAL_HOST: database.softwareshinobi.com

            LETSENCRYPT_HOST: database.softwareshinobi.com

##########################################
##
## API Server & Documentation
##
##########################################

    apis.softwareshinobi.com:

        container_name: apis.softwareshinobi.com
        
        image: softwareshinobi/apis.softwareshinobi.com

        depends_on:

           - shinobi-database

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: always

        ports:
            
            - "8888:8888"
            
        environment:

            DB_HOST: shinobi-database

            DB_NAME: shinobipublicapis

            DB_USER: shinobipublicapis

            DB_PASS: shinobipublicapis

            VIRTUAL_HOST: apis.softwareshinobi.com

            LETSENCRYPT_HOST: apis.softwareshinobi.com

    docs.apis.softwareshinobi.com:

        container_name: docs.apis.softwareshinobi.com

        image: softwareshinobi/docs.apis.softwareshinobi.com

        build: 

            context: docs

            dockerfile: Dockerfile

        restart: always

        ports:

            - "8880:80"

        environment:

            VIRTUAL_HOST: docs.apis.softwareshinobi.come

            LETSENCRYPT_HOST: docs.apis.softwareshinobi.com
